C:\Users\eran\PycharmProjects\python-mysql\venv\Scripts\python.exe C:/Users/eran/PycharmProjects/python-mysql/pan2.py
<mysql.connector.connection.MySQLConnection object at 0x0295C410>
Print select...
(4, 'Samsonic', 'pleasant', 'J')
(6, 'Panasung', 'oaktown', 'J')
(7, 'Samony', 'jackson', 'B')
(9, 'Orange', 'jackson', 'B')
(66, 'Eran', 'Magdiel', 'BKK6')
(77, 'Eran', 'Magdiel', 'xxx')
(88, 'Eran', 'Magdiel', 'BKK8')
(99, 'Eran', 'Magdiel', 'BKK8')
(88,)
(99,)
['88', '99']
The ids list : ['88', '99']
There are ids in list .. running update ...
UPDATE customer SET industry_type = %s WHERE id = %s('BKK10', '88')
1 record(s) affected
UPDATE customer SET industry_type = %s WHERE id = %s('BKK10', '99')
1 record(s) affected
Print select...
(4, 'Samsonic', 'pleasant', 'J')
(6, 'Panasung', 'oaktown', 'J')
(7, 'Samony', 'jackson', 'B')
(9, 'Orange', 'jackson', 'B')
(66, 'Eran', 'Magdiel', 'BKK6')
(77, 'Eran', 'Magdiel', 'xxx')
(88, 'Eran', 'Magdiel', 'BKK10')
(99, 'Eran', 'Magdiel', 'BKK10')

Process finished with exit code 0
